#!/usr/bin/env bash

# fnd is a search tool based on GREP


#functions
#how to use
usage() {
	printf "[USAGE] fnd \"pattern1|pattern2\" path/to/file \n"
}

# info preset
info() {
	printf "[INFO] %s\n" "$1"
}

# error preset
error() {
	printf "[ERROR] %s\n" "$1" >&2
}


#arguments
pattern="$1"
target="$2"


#start
#arguments check
	if [ -z "$pattern" ]; then
		error "no pattern input"
		usage
		printf " \n"
		exit 1
	fi


#file check
	if [ ! -f "$target" ]; then
		error "file \"$target\" not found"
		usage
		printf " \n"
		exit 1
	fi


#grep + result check
	if grep -E -i --color=auto "$pattern" "$target"; then
		printf " \n"
		exit 0
	else
		error "pattern \"$pattern\" not found in \"$target\""
		printf " \n"
		exit 1
	fi
